name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True
          persist-credentials: false

      - name: Invoke Webpack build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn install
          yarn build

      - name: Fix CNAME
        run: |
          echo ${{ secrets.CNAME }} > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          git-config-name: ${{ secrets.GIT_USER }}
          git-config-email: ${{ secrets.GIT_EMAIL }}
          clean: true
          single-commit: true
          silent: true
